name: "Scan Docker Images"
on: 
  push:
    branches:
      - main

jobs:
  AWS:
    name: Despliegue en AWS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Obteniendo código de repositorio"
        uses: actions/checkout@v3
      
      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target
      
      - name: "Dependency Check - SCA"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports'
  
      - name: "Verificar reporte"
        run: ls -ltra reports
  
      - name: "Instalando Horusec"
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
         
      - name: "Horusec - SAST"
        run: horusec start -p="./"
      
      - name: "Generación de imagen de docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test
          docker tag webgoat/test:latest public.ecr.aws/w2x5h8r5/Montse_DevSecOps:latest
          docker images
      
      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'webgoat/test'
          timeout: 10m0s
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          scanners: vuln,secret,config
        continue-on-error: true    
        
      - name: "Configuración de credenciales en AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MONTSE_PEM }}
          aws-region: us-east-2

      - name: "Subir imagen a ECR publico"
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w2x5h8r5
          docker push public.ecr.aws/w2x5h8r5/Montse_DEvSecOps:latest
            
      - name: "Scan Infra: Checkov"
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          directory: terraform
          framework: terraform
          soft_fail: true

      - name: "Aprovisianamiento con terraform"
        run: |
          cd terraform
          terraform init
          terraform plan -out tfplan
          terraform apply tfplan >> results_tfplan.txt
          ip_webgoat=$(cat results_tfplan.txt | grep "My_ip = " | awk '{ print $3 }' | sed 's/"//g')
          sed -i "s/IP/$ip_webgoat/g" ../ansible/inventario
          
      - name: "Ansible"
        env:
          PRIVATE_KEY: ${{ secrets.MONTSE_PEM }}
        run: |
          sudo apt update
          sudo apt install -y ansible
          cd Ansible
          echo "$PRIVATE_KEY" >> $HOME/key.pem
          sudo chmod 600 $HOME/key.pem
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventario server.yml --become --private-key $HOME/key.pem
          echo "Up server..."
          sleep 45
        continue-on-error: true
      
      - name: "Obtener Arachni - DAST"
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz  

      - name: "Evaluar aplicacion en contenedor - DAST"
        run: |
          ip_webgoat=$(cat terraform/results_tfplan.txt | grep "My_ip = " | awk '{ print $3 }' | sed 's/"//g')
          curl http://$ip_webgoat:8080/WebGoat/login
          ./arachni-1.6.1.3-0.6.1.1/bin/arachni --check=* http://$ip_webgoat:8080/WebGoat/login
        
      - name: "Destruccion de infraestructura"
        run: |
          cd terraform
          terraform plan -destroy -out tfplan
          terraform apply tfplan